SELECT SYSDATE + 1 FROM DUAL;  --系統日 + 1天
SELECT SYSDATE - 1 FROM DUAL;  --系統日 - 1天
SELECT SYSDATE + (1 / 1440 * 30) FROM DUAL ;-- (1440 = 24* 60)  因為加的都是天數 ，這邊就是 加30分鐘
SELECT ADD_MONTHS(SYSDATE, 1) FROM DUAL;  --系統日 +1個月
SELECT SYSDATE - (SYSDATE - 5) FROM DUAL;  --日期相減
SELECT MONTHS_BETWEEN(SYSDATE, (SYSDATE - 5)) FROM DUAL;  --日期相減(A, B) A - B的天數 (效果同上一行)