/****** Object:  StoredProcedure [dbo].[ManyTransaction5]    Script Date: 2024/4/8 上午 09:02:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[ManyTransaction5]
AS
BEGIN

    DECLARE @ID INT;
	
	-- 跑迴圈去執行第1步
	BEGIN TRANSACTION
		
		DECLARE ID_LIST Cursor FOR
		SELECT 9 AS ID
		UNION
		SELECT 10 AS ID;

		OPEN ID_LIST 

		--開始迴圈跑Cursor Start
		FETCH NEXT FROM ID_LIST INTO @ID
		WHILE (@@FETCH_STATUS <> -1)
		BEGIN

			INSERT INTO TableE (ID) VALUES (@ID);

			-- 讀取下一筆
			FETCH NEXT FROM ID_LIST INTO @ID
		END
        CLOSE ID_LIST
		DEALLOCATE ID_LIST
	COMMIT TRANSACTION

	-- 再執行會錯誤的
	BEGIN TRY
		
		BEGIN TRANSACTION

			DECLARE ID_LIST Cursor FOR
			SELECT 11 AS ID
			UNION
			SELECT 10 AS ID;

			OPEN ID_LIST 

			--開始迴圈跑Cursor Start
			FETCH NEXT FROM ID_LIST INTO @ID
			WHILE (@@FETCH_STATUS <> -1)
			BEGIN

				INSERT INTO TableE (ID) VALUES (@ID);

				-- 讀取下一筆
				FETCH NEXT FROM ID_LIST INTO @ID
			END
			CLOSE ID_LIST
			DEALLOCATE ID_LIST

		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
		BEGIN
			ROLLBACK TRANSACTION
		END 
	END CATCH
	

END
