-- 轉形
SELECT CAST('456' AS INT);
SELECT CAST('2024-01-20' AS DATETIME);
SELECT CAST(456 AS VARCHAR);

SELECT CONVERT(VARCHAR(8), GETDATE(), 112);
SELECT CONVERT(VARCHAR, GETDATE(), 114);
SELECT CONVERT(DATE, GETDATE(), 0);

-- 這個跟CAST一樣，基本用 CAST就行
SELECT PARSE('4000' AS INT);

SELECT FORMAT(GETDATE(), 'yyyy-MM-dd HH:mm:ss');